# Generated by Django 5.2.3 on 2025-07-03 21:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('NORTE', 'Norte'), ('SUR', 'Sur'), ('CENTRO', 'Centro'), ('VALLE CHILLOS', 'Valle de los Chillos'), ('CUMBAYA', 'Cumbayá'), ('TUMBACO', 'Tumbaco')], max_length=50)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('desde_donde', models.CharField(max_length=100)),
                ('hacia_donde', models.CharField(max_length=100)),
                ('numero_contacto', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
