# Generated by Django 5.2.3 on 2025-07-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carroscompartidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='numero_contacto',
            field=models.CharField(max_length=10),
        ),
    ]
