# Generated by Django 5.2.3 on 2025-07-03 23:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carroscompartidos', '0002_alter_anuncio_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='numero_contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EC'),
        ),
    ]
